{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "raps.fullname" . }}-aps-credentials
  namespace: {{ include "raps.namespace" . }}
  labels:
    {{- include "raps.labels" . | nindent 4 }}
spec:
  encryptedData:
    APS_CLIENT_ID: {{ .Values.sealedSecrets.apsCredentials.encryptedData.clientId | quote }}
    APS_CLIENT_SECRET: {{ .Values.sealedSecrets.apsCredentials.encryptedData.clientSecret | quote }}
{{- end }}
