apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "raps.fullname" . }}-worker
  namespace: {{ include "raps.namespace" . }}
  labels:
    {{- include "raps.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
