// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2025 Dmytro Yemelianov

//! CLI command modules
//!
//! Contains subcommand implementations for all APS operations.

pub mod acc;
pub mod admin;
pub mod api;
pub mod auth;
pub mod bucket;
pub mod cache;
pub mod config;
pub mod cost;
pub mod da;
#[cfg(feature = "dashboard")]
pub mod dashboard;
pub mod demo;
pub mod doctor;
pub mod docs;
pub mod folder;
pub mod generate;
pub mod hub;
pub mod init;
pub mod inspect;
pub mod interactive;
pub mod issue;
pub mod item;
pub mod job;
pub mod lint;
pub mod logs;
pub mod object;
pub mod pipeline;
pub mod plugin;
pub mod project;
pub mod reality;
pub mod report;
pub mod rfi;
pub mod schema;
#[cfg(feature = "kubernetes")]
pub mod serve;
pub mod snapshot;
pub mod stats;
pub mod status;
pub mod swarm;
pub mod sync;
pub mod template;
pub mod tracked;
pub mod translate;
pub mod watch_dir;
pub mod webhook;
pub mod workflow;

pub use acc::AccCommands;
pub use admin::AdminCommands;
pub use api::ApiCommands;
pub use auth::AuthCommands;
pub use bucket::BucketCommands;
pub use config::ConfigCommands;
pub use da::DaCommands;
pub use demo::DemoCommands;
pub use folder::FolderCommands;
pub use generate::GenerateArgs;
pub use hub::HubCommands;
pub use issue::IssueCommands;
pub use item::ItemCommands;
pub use job::JobCommands;
pub use object::ObjectCommands;
pub use pipeline::PipelineCommands;
pub use plugin::PluginCommands;
pub use project::ProjectCommands;
pub use reality::RealityCommands;
pub use report::ReportCommands;
pub use rfi::RfiCommands;
pub use snapshot::SnapshotCommands;
pub use template::TemplateCommands;
pub use translate::TranslateCommands;
pub use webhook::WebhookCommands;
pub use workflow::WorkflowCommands;
