// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2025 Dmytro Yemelianov

use std::collections::HashMap;

use super::CommandInfo;

/// Build the command tree based on RAPS CLI structure
pub fn build_command_tree() -> Vec<CommandInfo> {
    vec![
        CommandInfo {
            name: "auth",
            description: "Authentication commands",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "login",
                    description: "Authenticate with APS (2-legged or 3-legged)",
                    params: &[],
                    flags: &["--2lo", "--3lo", "--device", "--token <TOKEN>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "logout",
                    description: "Clear stored credentials",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "status",
                    description: "Show current authentication status",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "test",
                    description: "Test authentication by calling API",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "whoami",
                    description: "Show current user profile",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "inspect-token",
                    description: "Inspect current access token",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "bucket",
            description: "Bucket operations (OSS)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List all buckets",
                    params: &[],
                    flags: &["--limit <N>", "--offset <N>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "create",
                    description: "Create a new bucket",
                    params: &["<BUCKET_KEY>"],
                    flags: &["--retention <transient|temporary|persistent>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get bucket details",
                    params: &["<BUCKET_KEY>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "delete",
                    description: "Delete a bucket",
                    params: &["<BUCKET_KEY>"],
                    flags: &["--force"],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "object",
            description: "Object operations (OSS)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List objects in a bucket",
                    params: &["<BUCKET_KEY>"],
                    flags: &["--limit <N>", "--prefix <PREFIX>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "upload",
                    description: "Upload a file to a bucket",
                    params: &["<BUCKET_KEY>", "<FILE_PATH>"],
                    flags: &["--key <KEY>", "--batch", "--parallel"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "download",
                    description: "Download an object from a bucket",
                    params: &["<BUCKET_KEY>", "<OBJECT_KEY>"],
                    flags: &["--output <PATH>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "delete",
                    description: "Delete an object from a bucket",
                    params: &["<BUCKET_KEY>", "<OBJECT_KEY>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "details",
                    description: "Get object details",
                    params: &["<BUCKET_KEY>", "<OBJECT_KEY>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "signed-url",
                    description: "Generate signed download URL",
                    params: &["<BUCKET_KEY>", "<OBJECT_KEY>"],
                    flags: &["--minutes <N>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "urn",
                    description: "Get object URN for translation",
                    params: &["<BUCKET_KEY>", "<OBJECT_KEY>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "translate",
            description: "Model Derivative translation",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "start",
                    description: "Start a translation job",
                    params: &["<URN>"],
                    flags: &["--format <svf|svf2>", "--views <2d|3d>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "status",
                    description: "Check translation status",
                    params: &["<URN>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "manifest",
                    description: "Get translation manifest",
                    params: &["<URN>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "metadata",
                    description: "Get model metadata",
                    params: &["<URN>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "tree",
                    description: "Get model hierarchy tree",
                    params: &["<URN>"],
                    flags: &["--guid <GUID>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "properties",
                    description: "Get object properties",
                    params: &["<URN>"],
                    flags: &["--guid <GUID>", "--object-id <ID>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "delete",
                    description: "Delete translation manifest",
                    params: &["<URN>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "hub",
            description: "Hub operations (Data Management)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List accessible hubs",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get hub details",
                    params: &["<HUB_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "project",
            description: "Project operations (Data Management)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List projects in a hub",
                    params: &["<HUB_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get project details",
                    params: &["<HUB_ID>", "<PROJECT_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "folder",
            description: "Folder operations (Data Management)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List folder contents",
                    params: &["<PROJECT_ID>", "<FOLDER_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get folder details",
                    params: &["<PROJECT_ID>", "<FOLDER_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "create",
                    description: "Create a new folder",
                    params: &["<PROJECT_ID>", "<PARENT_FOLDER_ID>", "<NAME>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "item",
            description: "Item/file operations (Data Management)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "get",
                    description: "Get item details",
                    params: &["<PROJECT_ID>", "<ITEM_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "versions",
                    description: "List item versions",
                    params: &["<PROJECT_ID>", "<ITEM_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "webhook",
            description: "Webhook management",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List webhooks",
                    params: &[],
                    flags: &["--system <SYSTEM>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "create",
                    description: "Create a webhook",
                    params: &["<SYSTEM>", "<EVENT>", "<CALLBACK_URL>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get webhook details",
                    params: &["<SYSTEM>", "<EVENT>", "<HOOK_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "delete",
                    description: "Delete a webhook",
                    params: &["<SYSTEM>", "<EVENT>", "<HOOK_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "da",
            description: "Design Automation",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "engines",
                    description: "List available engines",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "appbundles",
                    description: "List app bundles",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "activities",
                    description: "List activities",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "workitems",
                    description: "List work items",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "issue",
            description: "ACC/BIM 360 Issues",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List issues in a project",
                    params: &["<PROJECT_ID>"],
                    flags: &["--status <STATUS>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get issue details",
                    params: &["<PROJECT_ID>", "<ISSUE_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "create",
                    description: "Create a new issue",
                    params: &["<PROJECT_ID>"],
                    flags: &["--title <TITLE>", "--type <TYPE>"],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "rfi",
            description: "ACC RFIs (Requests for Information)",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List RFIs in a project",
                    params: &["<PROJECT_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get RFI details",
                    params: &["<PROJECT_ID>", "<RFI_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "acc",
            description: "ACC extended modules",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "asset",
                    description: "Manage project assets",
                    params: &[],
                    flags: &[],
                    subcommands: &[
                        CommandInfo {
                            name: "list",
                            description: "List assets in a project",
                            params: &["<PROJECT_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "get",
                            description: "Get a specific asset",
                            params: &["<PROJECT_ID>", "<ASSET_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "create",
                            description: "Create a new asset",
                            params: &["<PROJECT_ID>"],
                            flags: &[
                                "--description <TEXT>",
                                "--barcode <TEXT>",
                                "--category-id <ID>",
                            ],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "update",
                            description: "Update an existing asset",
                            params: &["<PROJECT_ID>", "<ASSET_ID>"],
                            flags: &[
                                "--description <TEXT>",
                                "--barcode <TEXT>",
                                "--status-id <ID>",
                            ],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "delete",
                            description: "Delete an asset",
                            params: &["<PROJECT_ID>", "<ASSET_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                    ],
                },
                CommandInfo {
                    name: "submittal",
                    description: "Manage project submittals",
                    params: &[],
                    flags: &[],
                    subcommands: &[
                        CommandInfo {
                            name: "list",
                            description: "List submittals in a project",
                            params: &["<PROJECT_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "get",
                            description: "Get a specific submittal",
                            params: &["<PROJECT_ID>", "<SUBMITTAL_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "create",
                            description: "Create a new submittal",
                            params: &["<PROJECT_ID>"],
                            flags: &[
                                "--title <TEXT>",
                                "--spec-section <TEXT>",
                                "--due-date <DATE>",
                                "--from-csv <FILE>",
                            ],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "update",
                            description: "Update an existing submittal",
                            params: &["<PROJECT_ID>", "<SUBMITTAL_ID>"],
                            flags: &["--title <TEXT>", "--status <TEXT>", "--due-date <DATE>"],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "delete",
                            description: "Delete a submittal",
                            params: &["<PROJECT_ID>", "<SUBMITTAL_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                    ],
                },
                CommandInfo {
                    name: "checklist",
                    description: "Manage project checklists",
                    params: &[],
                    flags: &[],
                    subcommands: &[
                        CommandInfo {
                            name: "list",
                            description: "List checklists in a project",
                            params: &["<PROJECT_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "get",
                            description: "Get a specific checklist",
                            params: &["<PROJECT_ID>", "<CHECKLIST_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "create",
                            description: "Create a new checklist",
                            params: &["<PROJECT_ID>"],
                            flags: &[
                                "--title <TEXT>",
                                "--template-id <ID>",
                                "--location <TEXT>",
                                "--due-date <DATE>",
                                "--assignee-id <ID>",
                            ],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "update",
                            description: "Update an existing checklist",
                            params: &["<PROJECT_ID>", "<CHECKLIST_ID>"],
                            flags: &[
                                "--title <TEXT>",
                                "--status <TEXT>",
                                "--location <TEXT>",
                                "--due-date <DATE>",
                            ],
                            subcommands: &[],
                        },
                        CommandInfo {
                            name: "templates",
                            description: "List checklist templates",
                            params: &["<PROJECT_ID>"],
                            flags: &[],
                            subcommands: &[],
                        },
                    ],
                },
            ],
        },
        CommandInfo {
            name: "reality",
            description: "Reality Capture / Photogrammetry",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "jobs",
                    description: "List photoscene jobs",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "create",
                    description: "Create a photoscene",
                    params: &["<NAME>"],
                    flags: &["--format <FORMAT>"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "status",
                    description: "Check photoscene status",
                    params: &["<PHOTOSCENE_ID>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "config",
            description: "Configuration management",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "profile",
                    description: "Manage configuration profiles",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "get",
                    description: "Get configuration value",
                    params: &["<KEY>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "set",
                    description: "Set configuration value",
                    params: &["<KEY>", "<VALUE>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "migrate-tokens",
                    description: "Migrate tokens to secure storage",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "pipeline",
            description: "Run pipeline from YAML/JSON file",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "run",
                    description: "Execute a pipeline file",
                    params: &["<FILE>"],
                    flags: &["--dry-run"],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "validate",
                    description: "Validate a pipeline file",
                    params: &["<FILE>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "plugin",
            description: "Plugin management",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "list",
                    description: "List installed plugins",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "add",
                    description: "Add a plugin",
                    params: &["<NAME>", "<PATH>"],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "remove",
                    description: "Remove a plugin",
                    params: &["<NAME>"],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "demo",
            description: "Run demo scenarios",
            params: &[],
            flags: &[],
            subcommands: &[
                CommandInfo {
                    name: "bucket-lifecycle",
                    description: "Demo bucket lifecycle operations",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
                CommandInfo {
                    name: "model-pipeline",
                    description: "Demo model translation pipeline",
                    params: &[],
                    flags: &[],
                    subcommands: &[],
                },
            ],
        },
        CommandInfo {
            name: "generate",
            description: "Generate synthetic engineering files",
            params: &[],
            flags: &["--type <TYPE>", "--output <PATH>"],
            subcommands: &[],
        },
        CommandInfo {
            name: "completions",
            description: "Generate shell completions",
            params: &["<SHELL>"],
            flags: &[],
            subcommands: &[],
        },
        CommandInfo {
            name: "serve",
            description: "Start MCP server for AI integration",
            params: &[],
            flags: &[],
            subcommands: &[],
        },
        CommandInfo {
            name: "man",
            description: "Generate man pages",
            params: &[],
            flags: &["--output-dir <DIR>"],
            subcommands: &[],
        },
        CommandInfo {
            name: "help",
            description: "Show help for a command",
            params: &["[COMMAND]"],
            flags: &[],
            subcommands: &[],
        },
        CommandInfo {
            name: "exit",
            description: "Exit the interactive shell",
            params: &[],
            flags: &[],
            subcommands: &[],
        },
        CommandInfo {
            name: "quit",
            description: "Exit the interactive shell",
            params: &[],
            flags: &[],
            subcommands: &[],
        },
    ]
}

/// Build a flat map for quick lookup
pub fn build_command_map(commands: &[CommandInfo]) -> HashMap<String, CommandInfo> {
    let mut map = HashMap::new();

    for cmd in commands {
        map.insert(cmd.name.to_string(), cmd.clone());

        for subcmd in cmd.subcommands {
            let key = format!("{} {}", cmd.name, subcmd.name);
            map.insert(key, subcmd.clone());
        }
    }

    map
}
