openapi: 3.0.3
info:
  title: RAPS Pro Tier API
  version: 1.0.0
  description: |
    API contract for Pro tier (Enterprise) features in RAPS.
    Requires valid Pro tier license.
  
paths:
  /analytics/dashboard:
    get:
      summary: Get usage analytics dashboard
      operationId: analytics_dashboard
      tags:
        - Analytics
      parameters:
        - name: period
          in: query
          schema:
            type: string
            enum: [7d, 30d, 90d, 1y]
            default: 30d
      responses:
        '200':
          description: Analytics dashboard data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsDashboard'
        '402':
          description: Pro tier license required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /analytics/report:
    get:
      summary: Generate usage report
      operationId: analytics_report
      tags:
        - Analytics
      parameters:
        - name: period
          in: query
          required: true
          schema:
            type: string
        - name: format
          in: query
          schema:
            type: string
            enum: [json, csv, pdf]
            default: json
      responses:
        '200':
          description: Usage report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageReport'
  
  /audit/search:
    get:
      summary: Search audit logs
      operationId: audit_search
      tags:
        - Audit
      parameters:
        - name: user
          in: query
          schema:
            type: string
        - name: since
          in: query
          schema:
            type: string
            pattern: '^\d+d$'
            example: "7d"
        - name: command
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Audit log entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuditLogEntry'
  
  /audit/export:
    get:
      summary: Export audit logs in SIEM format
      operationId: audit_export
      tags:
        - Audit
      parameters:
        - name: format
          in: query
          schema:
            type: string
            enum: [cef, leef, json]
            default: cef
        - name: since
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Exported audit logs
          content:
            text/plain:
              schema:
                type: string
  
  /compliance/policy/reload:
    post:
      summary: Reload compliance policies
      operationId: compliance_policy_reload
      tags:
        - Compliance
      responses:
        '200':
          description: Policies reloaded successfully
  
  /tenant/switch:
    post:
      summary: Switch active tenant context
      operationId: tenant_switch
      tags:
        - Multi-tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Tenant name
      responses:
        '200':
          description: Tenant switched successfully
  
  /tenant/list:
    get:
      summary: List all configured tenants
      operationId: tenant_list
      tags:
        - Multi-tenant
      responses:
        '200':
          description: List of tenants
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenants:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tenant'

components:
  schemas:
    AnalyticsDashboard:
      type: object
      properties:
        period:
          type: string
        summary:
          type: object
          properties:
            total_api_calls:
              type: integer
            unique_users:
              type: integer
            total_data_transferred:
              type: integer
        by_endpoint:
          type: array
          items:
            type: object
            properties:
              endpoint:
                type: string
              calls:
                type: integer
        by_user:
          type: array
          items:
            type: object
            properties:
              user:
                type: string
              calls:
                type: integer
    
    UsageReport:
      type: object
      properties:
        period:
          type: string
        data:
          type: array
          items:
            type: object
    
    AuditLogEntry:
      type: object
      required:
        - timestamp
        - user
        - command
        - exit_code
      properties:
        timestamp:
          type: string
          format: date-time
        user:
          type: string
        command:
          type: string
        parameters:
          type: object
          description: Command parameters (secrets redacted)
        exit_code:
          type: integer
        outcome:
          type: string
          enum: [success, failure, error]
    
    Tenant:
      type: object
      required:
        - name
        - status
      properties:
        name:
          type: string
        status:
          type: string
          enum: [active, inactive]
        last_used:
          type: string
          format: date-time
        region:
          type: string
    
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "PRO_TIER_REQUIRED"
        message:
          type: string
          example: "This feature requires a Pro tier license"
