name = "raps-url-shortener"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "KV", id = "cadc9df0822044969e38611c20753c61" }
]

routes = [
  { pattern = "go.rapscli.xyz/*", zone_name = "rapscli.xyz" }
]

[vars]
BASE_URL = "https://go.rapscli.xyz"

# Secrets set via: wrangler secret put ADMIN_TOKEN
